title: 生如夏花般灿烂，死如秋叶般静美
author: Jeremy Young
email: yangyi1225@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  欲穷千里目，更上一层楼。
  欢迎您的到来

# social links
twitter_username: yangyi1225
github_username:  yangyi1225

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
